import { useState } from 'react';
import { Command, Palette, PanelsTopLeft } from 'lucide-react';
import { commandSpacing, commandTypography, mayadeenColorTokens } from '../../design-system/tokens';
import { Breadcrumb, Button, ConnectionStatus, DataTrustCard, DecisionTimeline, DialogFrame, DrawerFrame, EvidenceItem, IconButton, KpiCard, LoadingSkeleton, OperationalCard, SearchField, SegmentedControl, SeverityIndicator, SpatialLegend, SplitPane, StatusBadge, Toast, Tooltip, TruthBadge } from '../shared/CommandPrimitives';

const tokenGroups = [
  ['الأساس', ['canvas', 'surface1', 'surface2', 'surface3', 'borderSubtle', 'borderStrong']],
  ['النص والتفاعل', ['textPrimary', 'textSecondary', 'textMuted', 'brandPrimary', 'focusRing', 'spatialPrimary']],
  ['الحقيقة', ['truthVerified', 'truthReported', 'truthCandidate', 'truthScenario', 'truthUnknown']],
  ['الشدة', ['severityNormal', 'severityAttention', 'severityCritical', 'severityBlocked', 'severityInformation']]
] as const;

export function CommandVisualSystemWorkspace() {
  const [segment, setSegment] = useState<'overview' | 'states' | 'data'>('overview');
  return <div data-testid="command-visual-system-workspace" className="min-h-0 flex-1 overflow-y-auto command-scrollbar"><div className="mx-auto w-full max-w-[1920px] space-y-6 p-4 md:p-6"><header className="command-surface p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="command-eyebrow">مرجع تقني داخلي · lazy-loaded</p><h2 className="mt-2 text-2xl font-semibold text-command-text">نظام مَيادين المرئي للقيادة</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-command-muted">مرجع tokens وحالات المكونات. لا يمثل مساحة تشغيل يومية ولا يضيف صلاحيات أو بيانات أو قرارات.</p></div><StatusBadge severity="information" label="UI-only" icon={<Command className="h-3.5 w-3.5" />} /></div><div className="mt-5"><Breadcrumb items={['الإدارة التقنية', 'النظام المرئي', 'مرجع المكونات']} /></div></header>

    <section><div className="mb-3 flex items-center gap-2"><Palette className="h-4 w-4 text-command-accent" aria-hidden="true" /><h3 className="text-lg font-semibold text-command-text">لوحة الرموز الدلالية</h3></div><div className="grid gap-4 lg:grid-cols-2">{tokenGroups.map(([title, tokens]) => <OperationalCard key={title} title={title}>{<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{tokens.map((token) => <div key={token} className="rounded-md border border-command-line/70 bg-command-bg/40 p-3"><span className="mb-2 block h-9 rounded-sm" style={{ background: mayadeenColorTokens[token] }} /><p className="command-technical text-xs text-command-text">{token}</p><p className="command-technical mt-1 text-[11px] text-command-muted">{mayadeenColorTokens[token]}</p></div>)}</div>}</OperationalCard>)}</div></section>

    <SplitPane primary={<OperationalCard title="التحكم والحالات" eyebrow="لا لون بلا نص أو رمز"><div className="space-y-5"><div className="flex flex-wrap gap-2"><Button variant="primary">الإجراء الأساسي</Button><Button>إجراء ثانوي</Button><Button variant="quiet">إجراء هادئ</Button><Button variant="danger">إجراء حرج</Button><IconButton label="إجراء بأيقونة"><PanelsTopLeft className="h-4 w-4" /></IconButton><Tooltip label="تلميح مفهوم للمشغل"><span tabIndex={0} className="rounded px-2 py-1 text-xs text-command-muted ring-1 ring-command-line">مرر أو ركز</span></Tooltip></div><div className="flex flex-wrap gap-2"><TruthBadge truth="verified" /><TruthBadge truth="reported" /><TruthBadge truth="candidate" /><TruthBadge truth="scenario" /><TruthBadge truth="unknown" /></div><div className="flex flex-wrap gap-3"><SeverityIndicator severity="normal" label="طبيعي" /><SeverityIndicator severity="attention" label="يحتاج انتباهًا" /><SeverityIndicator severity="critical" label="حرج" /><SeverityIndicator severity="blocked" label="محجور" /></div><SegmentedControl label="عرض حالات المرجع" value={segment} onChange={setSegment} options={[{ value: 'overview', label: 'ملخص' }, { value: 'states', label: 'حالات' }, { value: 'data', label: 'بيانات' }]} /><SearchField label="حقل بحث" placeholder="نص عربي طويل قابل للقراءة" /></div></OperationalCard>} secondary={<div className="space-y-4"><DataTrustCard truth="reported" source="بيانات محلية منظمة" detail="تبقى مُبلّغ عنها وغير متحققة ولا تعدل خط الأساس." /><ConnectionStatus state="recovering" detail="تتم الاستعادة محليًا مع الحفاظ على مصدر الحالة." /><Toast title="تنبيه واجهة" message="المكون يعرض رسالة نصية مع دلالة لونية ورمز." /></div>} />

    <section className="grid gap-4 xl:grid-cols-3"><KpiCard label="مقياس منظم" value="٠" detail="لا بيانات مصطنعة في المعرض" /><KpiCard label="مساحة" value="2D / 3D" detail="العلاقة لا تعني اعتماد هندسة" tone="information" /><KpiCard label="ثقة" value="reported" detail="تمييز صريح عن verified" tone="attention" /></section>

    <section className="grid gap-4 xl:grid-cols-2"><OperationalCard title="الأدلة والقرار" eyebrow="مكونات محتوى كثيف"><div className="space-y-4"><EvidenceItem title="مرجع دليل محلي" source="مصدر منظم، لا يثبت تشغيلًا ميدانيًا" /><DecisionTimeline items={[{ title: 'تجميع الحالة', detail: 'سجل منظم مع وقت ومصدر واضحين.', severity: 'information' }, { title: 'قرار بشري', detail: 'لا اعتماد تلقائي من واجهة العرض.', severity: 'attention' }]} /></div></OperationalCard><OperationalCard title="المكان" eyebrow="ترميز مكاني منفصل"><SpatialLegend /><div className="mt-5 h-24 rounded-md border border-dashed border-command-quiet bg-command-bg/40 p-4 text-xs text-command-muted">هندسة مرجعية: لا تضيف هذه اللوحة إحداثيات أو اعتمادًا مكانيًا.</div></OperationalCard></section>

    <section className="grid gap-4 xl:grid-cols-3"><OperationalCard title="تحميل"><div className="space-y-3"><LoadingSkeleton className="h-4 w-2/5" /><LoadingSkeleton className="h-3 w-full" /><LoadingSkeleton className="h-3 w-4/5" /></div></OperationalCard><DialogFrame title="حوار مرجعي"><p className="text-sm leading-6 text-command-muted">العناوين، الفوكس، ومحتوى RTL تبقى ثابتة في الحوارات.</p></DialogFrame><DrawerFrame title="درج مرجعي"><p className="text-xs leading-6 text-command-muted">يُستخدم للمعلومات الثانوية فقط.</p></DrawerFrame></section>

    <footer className="command-card p-4 text-xs leading-6 text-command-muted"><p>المسافات: <span className="command-technical">{commandSpacing.join(' · ')} px</span></p><p className="mt-1">الطباعة: <span className="command-technical">{Object.entries(commandTypography).map(([name, value]) => `${name} ${value}`).join(' · ')}</span></p></footer>
  </div></div>;
}
